### ISSUE TITLE
OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by harsh204016** [douglas125/SpeechCmdRecognition#1]
**I am using colab**
earlystopper = EarlyStopping(monitor='val_sparse_categorical_accuracy', patience=10, verbose=1)
checkpointer = ModelCheckpoint('model-attRNN.h5', monitor='val_sparse_categorical_accuracy', verbose=1, save_best_only=True)
results = model.fit_generator(trainGen, validation_data = valGen, epochs = 40, use_multiprocessing=True, workers=4,
                    callbacks=[earlystopper, checkpointer, lrate])

**when I am running this cell then I am getting this error:**
Then after two epochs 

Epoch 1/40
Changing learning rate to 0.001
797/798 [============================>.] - ETA: 0s - loss: 0.8792 - sparse_categorical_accuracy: 0.7550Epoch 1/40
798/798 [==============================] - 62s 78ms/step - loss: 0.8786 - sparse_categorical_accuracy: 0.7551 - val_loss: 0.3697 - val_sparse_categorical_accuracy: 0.8987

Epoch 00001: val_sparse_categorical_accuracy improved from -inf to 0.89873, saving model to model-attRNN.h5
Epoch 1/40
Epoch 2/40
Changing learning rate to 0.001
798/798 [==============================] - 59s 73ms/step - loss: 0.3006 - sparse_categorical_accuracy: 0.9176 - val_loss: 0.3205 - val_sparse_categorical_accuracy: 0.9061

Epoch 00002: val_sparse_categorical_accuracy improved from 0.89873 to 0.90610, saving model to model-attRNN.h5
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-691684d28f62> in <module>()
      2 checkpointer = ModelCheckpoint('model-attRNN.h5', monitor='val_sparse_categorical_accuracy', verbose=1, save_best_only=True)
      3 results = model.fit_generator(trainGen, validation_data = valGen, epochs = 40, use_multiprocessing=True, workers=4,
----> 4                     callbacks=[earlystopper, checkpointer, lrate])

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    146         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    147     elif mode == 'w':
--> 148         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
    149     elif mode == 'a':
    150         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

**Comment by douglas125** [comment]
Looks like an OS error to me...

Have you tried `save_weights_only=True` in ModelCheckpoint callback?

**Comment by douglas125** [comment]
The current version should fix it. Closing, but feel free to reopen.
