### ISSUE TITLE
issues with ConvSpeechModel tensorflow version

### ISSUE THREAD

**Issue by prasanna10** [douglas125/SpeechCmdRecognition#10]
what is the exact tensorflow version used which will solve this error of dense input shape Im using this 2.0.0 but still no solution

**Comment by Anurag-Varma** [comment]
AssertionError: Hey! The input is too short!

getting the above error in the line:-

model = SpeechModels.AttRNNSpeechModel(nCategories=nCategs, samplingrate = sr, inputLength = None)#, rnn_func=L.LSTM)



UPDATE: solved it by using tensorflow 2.7.0, previously used 1.15.0 and got the above error

**Comment by douglas125** [comment]
Thanks for that. Closing.
(For some reason I sometimes don't get github msgs on issues)
