### ISSUE TITLE
OSError: couldn't find .h5 file in the directory

### ISSUE THREAD

**Issue by abeselomg** [douglas125/SpeechCmdRecognition#2]
I was running the model and i encountered the following error.
OSError: Unable to open file (unable to open file: name = 'model-attRNN.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by douglas125** [comment]
I encountered that error too.

The current version should fix it - I think it may have to do with the checkpointing.

Feel free to reopen if it is still a problem.
