### ISSUE TITLE
librosa and kapre missing from requirements.txt

### ISSUE THREAD

**Issue by mueller91** [douglas125/SpeechCmdRecognition#4]
also, soundfile does not install if forced to use specific version (remove =0.10 in requirements.txt fixed issue)

**Comment by douglas125** [comment]
nice catch, I'll be on it

**Comment by douglas125** [comment]
oh I think the change to tf 2.0 fixes this

tensorflow>=2
kapre>=0.1.7
pandas>=0.25
librosa>=0.6
tqdm
matplotlib

feel free to re-open if needed
