### ISSUE TITLE
Can you please share the model_weights files (.h5 or .pb) ?

### ISSUE THREAD

**Issue by AV-CSE31** [douglas125/SpeechCmdRecognition#6]

**Comment by douglas125** [comment]
Sorry for the late answer.

If you run the notebook using Colab you can choose what kind of model you want (ie, what words you want to recognize, for example)

There are so many combinations that I didn't bother.

But I could get a run going and pick up some pretrained weights.

**Comment by douglas125** [comment]
This last commit has pretrained weights for 35 words. Closing, but feel free to open another issue if needed.

**Comment by AV-CSE31** [comment]
Thanks
