### ISSUE TITLE
issues with ConvSpeechModel

### ISSUE THREAD

**Issue by ilanzylberberg** [douglas125/SpeechCmdRecognition#9]
Hi Douglas,
I am re-opening the issue that I asked before.
I am trying to run ConvSpeechModel,
model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, inputLength= 16000)
and I got:
raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

That seems to be because before the Dense we have:
max_pooling2d_2 (MaxPooling2 (None, None, 20, 80)      

If I run it without the flatten I got the following summary :
'''
(32, 80, 125, 1)
Model: "ConvSpeechModel"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 16000)]           0         
_________________________________________________________________
reshape (Reshape)            (None, 1, None)           0         
_________________________________________________________________
mel_stft (Melspectrogram)    (None, 80, None, 1)       1091664   
_________________________________________________________________
normalization2d_1 (Normaliza (None, 80, None, 1)       0         
_________________________________________________________________
permute (Permute)            (None, None, 80, 1)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, None, 80, 20)      120       
_________________________________________________________________
batch_normalization (BatchNo (None, None, 80, 20)      80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, None, 80, 20)      0         
_________________________________________________________________
dropout (Dropout)            (None, None, 80, 20)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, None, 80, 40)      7240      
_________________________________________________________________
batch_normalization_1 (Batch (None, None, 80, 40)      160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, None, 40, 40)      0         
_________________________________________________________________
dropout_1 (Dropout)          (None, None, 40, 40)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, None, 40, 80)      28880     
_________________________________________________________________
batch_normalization_2 (Batch (None, None, 40, 80)      320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, None, 20, 80)      0         
_________________________________________________________________
dense (Dense)                (None, None, 20, 64)      5184      
_________________________________________________________________
dense_1 (Dense)              (None, None, 20, 32)      2080      
_________________________________________________________________
dense_2 (Dense)              (None, None, 20, 12)      396       
=================================================================
Total params: 1,136,124
Trainable params: 1,135,844
Non-trainable params: 280
'''
and Without the Flatten also does not work:

''tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [32,1] vs. [32,15,20]''

Do you know how to overcome this issue?

**Comment by ilanzylberberg** [comment]
Issue resolved!
as you told in the past probably a Tensorflow version issue.
I was using 2.2.0 and it was failing.
Tks

**Comment by prasanna10** [comment]
> Hi Douglas,
> I am re-opening the issue that I asked before.
> I am trying to run ConvSpeechModel,
> model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, inputLength= 16000)
> and I got:
> raise ValueError('The last dimension of the inputs to `Dense` '
> ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
> 
> That seems to be because before the Dense we have:
> max_pooling2d_2 (MaxPooling2 (None, None, 20, 80)
> 
> If I run it without the flatten I got the following summary :
> '''
> (32, 80, 125, 1)
> Model: "ConvSpeechModel"
> 
> # Layer (type) Output Shape Param #
> input_1 (InputLayer) [(None, 16000)] 0
> 
> reshape (Reshape) (None, 1, None) 0
> 
> mel_stft (Melspectrogram) (None, 80, None, 1) 1091664
> 
> normalization2d_1 (Normaliza (None, 80, None, 1) 0
> 
> permute (Permute) (None, None, 80, 1) 0
> 
> conv2d (Conv2D) (None, None, 80, 20) 120
> 
> batch_normalization (BatchNo (None, None, 80, 20) 80
> 
> max_pooling2d (MaxPooling2D) (None, None, 80, 20) 0
> 
> dropout (Dropout) (None, None, 80, 20) 0
> 
> conv2d_1 (Conv2D) (None, None, 80, 40) 7240
> 
> batch_normalization_1 (Batch (None, None, 80, 40) 160
> 
> max_pooling2d_1 (MaxPooling2 (None, None, 40, 40) 0
> 
> dropout_1 (Dropout) (None, None, 40, 40) 0
> 
> conv2d_2 (Conv2D) (None, None, 40, 80) 28880
> 
> batch_normalization_2 (Batch (None, None, 40, 80) 320
> 
> max_pooling2d_2 (MaxPooling2 (None, None, 20, 80) 0
> 
> dense (Dense) (None, None, 20, 64) 5184
> 
> dense_1 (Dense) (None, None, 20, 32) 2080
> 
> # dense_2 (Dense) (None, None, 20, 12) 396
> Total params: 1,136,124
> Trainable params: 1,135,844
> Non-trainable params: 280
> '''
> and Without the Flatten also does not work:
> 
> ''tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1] vs. [32,15,20]''
> 
> Do you know how to overcome this issue?

which is the exact version of tensorflow that will resolve this issue. I am using 2.0.0 but still finding the same issue
